version: "3.8"
services:
  web:
    image: nginx:latest # последняя версия nginx
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf # путь до конфигурационного файла
    links: # привязываем сервис
      - ambrial
  ambrial: # не имя, но сойдёт
    image : php:8.3-fpm
